// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var LetOps = require("../library/LetOps.js");
var Globals = require("../library/Globals.js");
var ERC20Mock = require("../library/contracts/ERC20Mock.js");
var ClaimAaveRewards = require("./yieldManager/ClaimAaveRewards.js");
var YieldManagerAave = require("../library/contracts/YieldManagerAave.js");
var Smock = require("@eth-optimism/smock");
var LendingPoolAaveMock = require("../library/contracts/LendingPoolAaveMock.js");
var AaveIncentivesControllerMock = require("../library/contracts/AaveIncentivesControllerMock.js");

describe("Float System", (function () {
        var accounts = {
          contents: undefined
        };
        var contracts = {
          contents: undefined
        };
        var setup = function (param) {
          return LetOps.AwaitThen.let_(ethers.getSigners(), (function (loadedAccounts) {
                        accounts.contents = loadedAccounts;
                        var treasury = loadedAccounts[1];
                        var longShortAddress = ethers.Wallet.createRandom().address;
                        var fundTokenAddress = ethers.Wallet.createRandom().address;
                        return LetOps.Await.let_(LendingPoolAaveMock.make(undefined), (function (lendingPoolMock) {
                                      return LetOps.Await.let_(Smock.smockit(lendingPoolMock), (function (lendingPoolSmocked) {
                                                    return LetOps.Await.let_(ERC20Mock.make("Payment Token Mock", "PaymentToken"), (function (paymentTokenMock) {
                                                                  return LetOps.Await.let_(Smock.smockit(paymentTokenMock), (function (paymentTokenSmocked) {
                                                                                return LetOps.Await.let_(ERC20Mock.make("Test APaymentToken", "APaymentToken"), (function (erc20Mock) {
                                                                                              return LetOps.Await.let_(AaveIncentivesControllerMock.make(undefined), (function (aaveIncentivesControllerMock) {
                                                                                                            return LetOps.Await.let_(Smock.smockit(aaveIncentivesControllerMock), (function (aaveIncentivesControllerSmocked) {
                                                                                                                          return LetOps.Await.let_(YieldManagerAave.make(longShortAddress, treasury.address, paymentTokenSmocked.address, fundTokenAddress, lendingPoolSmocked.address, aaveIncentivesControllerSmocked.address, 6543), (function (yieldManagerAave) {
                                                                                                                                        contracts.contents = {
                                                                                                                                          erc20Mock: erc20Mock,
                                                                                                                                          yieldManagerAave: yieldManagerAave,
                                                                                                                                          paymentToken: paymentTokenSmocked,
                                                                                                                                          treasury: treasury,
                                                                                                                                          aaveIncentivesController: aaveIncentivesControllerSmocked
                                                                                                                                        };
                                                                                                                                        
                                                                                                                                      }));
                                                                                                                        }));
                                                                                                          }));
                                                                                            }));
                                                                              }));
                                                                }));
                                                  }));
                                    }));
                      }));
        };
        Globals.describeUnit("(un-optimised) YieldManagerAave - internals exposed", (function (param) {
                beforeEach(function () {
                      return setup(undefined);
                    });
                
              }));
        return Globals.describeUnit("(optimised) YieldManagerAave - internals exposed ", (function (param) {
                      before(function () {
                            return setup(undefined);
                          });
                      return ClaimAaveRewards.testUnit(contracts);
                    }));
      }));

/*  Not a pure module */
