import { Contracts } from '../../existingContracts/compound.json';

import {
    ChainLinkAggregators,
    WBTCWhale,
    WhaleAccount,
    UNIWhale,
    INCHWhale,
    DAI_Yearn_Protocol_Address,
    WBTC_Yearn_Protocol_Address,
    USDC_Yearn_Protocol_Address,
    USDT_Yearn_Protocol_Address,
    INCH_Token_Address,
    INCH_Yearn_Protocol_Address,
    HEGIC_Token_Address,
    HEGIC_Yearn_Protocol_Address,
} from '../constants';

export const psYearnTestCases = [
    {
        Amount: 1,
        Whale1: WBTCWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.DAI,
        CollateralTokenParam: Contracts.WBTC,
        liquidityBorrowTokenParam: DAI_Yearn_Protocol_Address,
        liquidityCollateralTokenParam: WBTC_Yearn_Protocol_Address,
        chainlinkBorrowParam: ChainLinkAggregators['DAI/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['BTC/USD'],
    },
    {
        Amount: 1,
        Whale1: WBTCWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.USDC,
        CollateralTokenParam: Contracts.WBTC,
        liquidityBorrowTokenParam: USDC_Yearn_Protocol_Address,
        liquidityCollateralTokenParam: WBTC_Yearn_Protocol_Address,
        chainlinkBorrowParam: ChainLinkAggregators['USDC/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['BTC/USD'],
    },
    {
        Amount: 1,
        Whale1: WBTCWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.USDT,
        CollateralTokenParam: Contracts.WBTC,
        liquidityBorrowTokenParam: USDT_Yearn_Protocol_Address,
        liquidityCollateralTokenParam: WBTC_Yearn_Protocol_Address,
        chainlinkBorrowParam: ChainLinkAggregators['USDT/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['BTC/USD'],
    },
    {
        Amount: 1,
        Whale1: WBTCWhale,
        Whale2: INCHWhale,
        BorrowTokenParam: INCH_Token_Address,
        CollateralTokenParam: Contracts.WBTC,
        liquidityBorrowTokenParam: INCH_Yearn_Protocol_Address,
        liquidityCollateralTokenParam: WBTC_Yearn_Protocol_Address,
        chainlinkBorrowParam: ChainLinkAggregators['INCH/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['BTC/USD'],
    },
    {
        Amount: 10,
        Whale1: UNIWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: HEGIC_Token_Address,
        CollateralTokenParam: Contracts.WBTC,
        liquidityBorrowTokenParam: HEGIC_Yearn_Protocol_Address,
        liquidityCollateralTokenParam: WBTC_Yearn_Protocol_Address,
        chainlinkBorrowParam: ChainLinkAggregators['HEGIC/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['BTC/USD'],
    },
];
