// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Chai = require("../../bindings/chai/Chai.js");
var LetOps = require("../../library/LetOps.js");
var Globals = require("../../library/Globals.js");
var Helpers = require("../../library/Helpers.js");
var Contract = require("../../library/Contract.js");
var Smock = require("@eth-optimism/smock");
var SyntheticTokenSmocked = require("../../library/smock/SyntheticTokenSmocked.js");
var YieldManagerMockSmocked = require("../../library/smock/YieldManagerMockSmocked.js");

function testUnit(contracts, param) {
  return Globals.describeUnit("Execute next price action", (function (param) {
                var marketIndex = Helpers.randomJsInteger(undefined);
                var user = Helpers.randomAddress(undefined);
                describe("_executeOutstandingNextPriceMints", (function () {
                        var longSynthSmocked = {
                          contents: undefined
                        };
                        var shortSynthSmocked = {
                          contents: undefined
                        };
                        var longShortRef = {
                          contents: ""
                        };
                        var setup = function (isLong, userNextPrice_syntheticToken_redeemAmount, userNextPrice_currentUpdateIndex, syntheticToken_priceSnapshot) {
                          var match = contracts.contents;
                          var longShort = match.longShort;
                          var match$1 = match.markets[0];
                          var shortSynth = match$1.shortSynth;
                          longShortRef.contents = longShort;
                          return LetOps.Await.let_(Smock.smockit(match$1.longSynth), (function (smockedLongSynth) {
                                        return LetOps.Await.let_(Smock.smockit(shortSynth), (function (smockedShortSynth) {
                                                      SyntheticTokenSmocked.mockTransferToReturn(smockedLongSynth, true);
                                                      SyntheticTokenSmocked.mockTransferToReturn(smockedShortSynth, true);
                                                      longSynthSmocked.contents = smockedLongSynth;
                                                      shortSynthSmocked.contents = smockedShortSynth;
                                                      return longShort.setExecuteOutstandingNextPriceMintsGlobals(marketIndex, user, isLong, (
                                                                  isLong ? smockedLongSynth : smockedShortSynth
                                                                ).address, userNextPrice_syntheticToken_redeemAmount, userNextPrice_currentUpdateIndex, syntheticToken_priceSnapshot);
                                                    }));
                                      }));
                        };
                        var testExecuteOutstandingNextPriceMints = function (isLong) {
                          describe("userNextPriceDepositAmount == 0", (function () {
                                  var executeOutstandingNextPriceMintsTx = {
                                    contents: "Undefined"
                                  };
                                  beforeEach(function () {
                                        return LetOps.Await.let_(setup(isLong, Globals.zeroBn, Helpers.randomInteger(undefined), Helpers.randomTokenAmount(undefined)), (function (param) {
                                                      executeOutstandingNextPriceMintsTx.contents = contracts.contents.longShort._executeOutstandingNextPriceMintsExposed(marketIndex, user, isLong);
                                                      
                                                    }));
                                      });
                                  it("should not call any functions or change any state", (function () {
                                          return LetOps.Await.let_(executeOutstandingNextPriceMintsTx.contents, (function (param) {
                                                        var transferCalls = SyntheticTokenSmocked.transferCalls((
                                                              isLong ? longSynthSmocked : shortSynthSmocked
                                                            ).contents);
                                                        return Chai.recordArrayDeepEqualFlat(undefined, transferCalls, []);
                                                      }));
                                        }));
                                  it("should not emit the ExecuteNextPriceMintSettlementUser event", (function () {
                                          return Chai.expectToNotEmit(Chai.callEmitEvents(executeOutstandingNextPriceMintsTx.contents, contracts.contents.longShort, "ExecuteNextPriceMintSettlementUser"));
                                        }));
                                  
                                }));
                          describe("userNextPriceDepositAmount > 0", (function () {
                                  var executeOutstandingNextPriceMintsTx = {
                                    contents: "Undefined"
                                  };
                                  var userNextPrice_syntheticToken_redeemAmount = Helpers.randomTokenAmount(undefined);
                                  var syntheticToken_priceSnapshot = Helpers.randomTokenAmount(undefined);
                                  beforeEach(function () {
                                        return LetOps.Await.let_(setup(isLong, userNextPrice_syntheticToken_redeemAmount, Helpers.randomInteger(undefined), syntheticToken_priceSnapshot), (function (param) {
                                                      executeOutstandingNextPriceMintsTx.contents = contracts.contents.longShort._executeOutstandingNextPriceMintsExposed(marketIndex, user, isLong);
                                                      
                                                    }));
                                      });
                                  it("should call transfer on the correct amount of synthetic tokens to the user", (function () {
                                          return LetOps.Await.let_(executeOutstandingNextPriceMintsTx.contents, (function (param) {
                                                        var transferCalls = SyntheticTokenSmocked.transferCalls((
                                                              isLong ? longSynthSmocked : shortSynthSmocked
                                                            ).contents);
                                                        var expectedAmountOfSynthToRecieve = Contract.LongShortHelpers.calcAmountSyntheticToken(userNextPrice_syntheticToken_redeemAmount, syntheticToken_priceSnapshot);
                                                        return Chai.recordArrayDeepEqualFlat(undefined, transferCalls, [{
                                                                      recipient: user,
                                                                      amount: expectedAmountOfSynthToRecieve
                                                                    }]);
                                                      }));
                                        }));
                                  it("should emit the ExecuteNextPriceMintSettlementUser event with the correct arguments", (function () {
                                          var expectedAmountOfSynthToRecieve = Contract.LongShortHelpers.calcAmountSyntheticToken(userNextPrice_syntheticToken_redeemAmount, syntheticToken_priceSnapshot);
                                          return Chai.callEmitEvents(executeOutstandingNextPriceMintsTx.contents, contracts.contents.longShort, "ExecuteNextPriceMintSettlementUser").withArgs(user, marketIndex, isLong, expectedAmountOfSynthToRecieve);
                                        }));
                                  it("should reset userNextPriceDepositAmount to zero", (function () {
                                          return LetOps.Await.let_(contracts.contents.longShort.userNextPrice_paymentToken_depositAmount(marketIndex, isLong, user), (function (userNextPriceDepositAmount) {
                                                        return Chai.bnEqual(undefined, Globals.zeroBn, userNextPriceDepositAmount);
                                                      }));
                                        }));
                                  
                                }));
                          
                        };
                        describe("Long Side", (function () {
                                return testExecuteOutstandingNextPriceMints(true);
                              }));
                        describe("Short Side", (function () {
                                return testExecuteOutstandingNextPriceMints(false);
                              }));
                        
                      }));
                describe("_executeOutstandingNextPriceRedeems", (function () {
                        var yieldManagerSmocked = {
                          contents: undefined
                        };
                        var setup = function (isLong, userNextPrice_syntheticToken_redeemAmount, userNextPrice_currentUpdateIndex, syntheticToken_priceSnapshot) {
                          var match = contracts.contents;
                          var longShort = match.longShort;
                          var match$1 = match.markets[0];
                          return LetOps.Await.let_(Smock.smockit(match$1.yieldManager), (function (smockedYieldManeger) {
                                        yieldManagerSmocked.contents = smockedYieldManeger;
                                        return longShort.setExecuteOutstandingNextPriceRedeemsGlobals(marketIndex, user, isLong, smockedYieldManeger.address, userNextPrice_syntheticToken_redeemAmount, userNextPrice_currentUpdateIndex, syntheticToken_priceSnapshot);
                                      }));
                        };
                        var testExecuteOutstandingNextPriceRedeems = function (isLong) {
                          describe("userNextPriceDepositAmount == 0", (function () {
                                  var executeOutstandingNextPriceRedeemsTx = {
                                    contents: "Undefined"
                                  };
                                  beforeEach(function () {
                                        return LetOps.Await.let_(setup(isLong, Globals.zeroBn, Helpers.randomInteger(undefined), Helpers.randomTokenAmount(undefined)), (function (param) {
                                                      executeOutstandingNextPriceRedeemsTx.contents = contracts.contents.longShort._executeOutstandingNextPriceRedeemsExposed(marketIndex, user, isLong);
                                                      
                                                    }));
                                      });
                                  it("should not call any functions or change any state", (function () {
                                          return LetOps.Await.let_(executeOutstandingNextPriceRedeemsTx.contents, (function (param) {
                                                        var transferCalls = YieldManagerMockSmocked.transferPaymentTokensToUserCalls(yieldManagerSmocked.contents);
                                                        return Chai.recordArrayDeepEqualFlat(undefined, transferCalls, []);
                                                      }));
                                        }));
                                  it("should not emit the ExecuteNextPriceRedeemSettlementUser event", (function () {
                                          return Chai.expectToNotEmit(Chai.callEmitEvents(executeOutstandingNextPriceRedeemsTx.contents, contracts.contents.longShort, "ExecuteNextPriceRedeemSettlementUser"));
                                        }));
                                  
                                }));
                          describe("userNextPriceDepositAmount > 0", (function () {
                                  var executeOutstandingNextPriceRedeemsTx = {
                                    contents: "Undefined"
                                  };
                                  var userNextPrice_syntheticToken_redeemAmount = Helpers.randomTokenAmount(undefined);
                                  var syntheticToken_priceSnapshot = Helpers.randomTokenAmount(undefined);
                                  beforeEach(function () {
                                        return LetOps.Await.let_(setup(isLong, userNextPrice_syntheticToken_redeemAmount, Helpers.randomInteger(undefined), syntheticToken_priceSnapshot), (function (param) {
                                                      executeOutstandingNextPriceRedeemsTx.contents = contracts.contents.longShort._executeOutstandingNextPriceRedeemsExposed(marketIndex, user, isLong);
                                                      
                                                    }));
                                      });
                                  it("should call transfer on the correct amount of Payment Tokens to the user", (function () {
                                          return LetOps.Await.let_(executeOutstandingNextPriceRedeemsTx.contents, (function (param) {
                                                        var transferCalls = YieldManagerMockSmocked.transferPaymentTokensToUserCalls(yieldManagerSmocked.contents);
                                                        var expectedAmountOfPaymentTokenToRecieve = Contract.LongShortHelpers.calcAmountPaymentToken(userNextPrice_syntheticToken_redeemAmount, syntheticToken_priceSnapshot);
                                                        return Chai.recordArrayDeepEqualFlat(undefined, transferCalls, [{
                                                                      user: user,
                                                                      amount: expectedAmountOfPaymentTokenToRecieve
                                                                    }]);
                                                      }));
                                        }));
                                  it("should emit the ExecuteNextPriceRedeemSettlementUser event with the correct arguments", (function () {
                                          var expectedAmountOfPaymentTokenToRecieve = Contract.LongShortHelpers.calcAmountPaymentToken(userNextPrice_syntheticToken_redeemAmount, syntheticToken_priceSnapshot);
                                          return Chai.callEmitEvents(executeOutstandingNextPriceRedeemsTx.contents, contracts.contents.longShort, "ExecuteNextPriceRedeemSettlementUser").withArgs(user, marketIndex, isLong, expectedAmountOfPaymentTokenToRecieve);
                                        }));
                                  it("should reset userNextPriceDepositAmount to zero", (function () {
                                          return LetOps.Await.let_(contracts.contents.longShort.userNextPrice_paymentToken_depositAmount(marketIndex, isLong, user), (function (userNextPriceDepositAmount) {
                                                        return Chai.bnEqual(undefined, Globals.zeroBn, userNextPriceDepositAmount);
                                                      }));
                                        }));
                                  
                                }));
                          
                        };
                        describe("Long Side", (function () {
                                return testExecuteOutstandingNextPriceRedeems(true);
                              }));
                        describe("Short Side", (function () {
                                return testExecuteOutstandingNextPriceRedeems(false);
                              }));
                        
                      }));
                describe("_executeOutstandingNextPriceTokenShifts", (function () {
                        var longSynthSmocked = {
                          contents: undefined
                        };
                        var shortSynthSmocked = {
                          contents: undefined
                        };
                        var setup = function (isShiftFromLong, userNextPrice_syntheticToken_toShiftAwayFrom_marketSide, userNextPrice_currentUpdateIndex, syntheticToken_priceSnapshotShiftedFrom, syntheticToken_priceSnapshotShiftedTo) {
                          var match = contracts.contents;
                          var longShort = match.longShort;
                          var match$1 = match.markets[0];
                          var shortSynth = match$1.shortSynth;
                          return LetOps.Await.let_(Smock.smockit(match$1.longSynth), (function (smockedLongSynth) {
                                        return LetOps.Await.let_(Smock.smockit(shortSynth), (function (smockedShortSynth) {
                                                      SyntheticTokenSmocked.mockTransferToReturn(smockedLongSynth, true);
                                                      SyntheticTokenSmocked.mockTransferToReturn(smockedShortSynth, true);
                                                      longSynthSmocked.contents = smockedLongSynth;
                                                      shortSynthSmocked.contents = smockedShortSynth;
                                                      return longShort.setExecuteOutstandingNextPriceTokenShiftsGlobals(marketIndex, user, isShiftFromLong, (
                                                                  isShiftFromLong ? smockedShortSynth : smockedLongSynth
                                                                ).address, userNextPrice_syntheticToken_toShiftAwayFrom_marketSide, userNextPrice_currentUpdateIndex, syntheticToken_priceSnapshotShiftedFrom, syntheticToken_priceSnapshotShiftedTo);
                                                    }));
                                      }));
                        };
                        var testExecuteOutstandingNextPriceRedeems = function (isShiftFromLong) {
                          describe("syntheticToken_toShiftAwayFrom_marketSide == 0", (function () {
                                  var executeOutstandingNextPriceRedeemsTx = {
                                    contents: "Undefined"
                                  };
                                  beforeEach(function () {
                                        return LetOps.Await.let_(setup(isShiftFromLong, Globals.zeroBn, Helpers.randomInteger(undefined), Helpers.randomTokenAmount(undefined), Helpers.randomTokenAmount(undefined)), (function (param) {
                                                      executeOutstandingNextPriceRedeemsTx.contents = contracts.contents.longShort._executeOutstandingNextPriceTokenShiftsExposed(marketIndex, user, isShiftFromLong);
                                                      
                                                    }));
                                      });
                                  it("should not call any functions or change any state", (function () {
                                          return LetOps.Await.let_(executeOutstandingNextPriceRedeemsTx.contents, (function (param) {
                                                        var transferCalls = SyntheticTokenSmocked.transferCalls((
                                                              isShiftFromLong ? shortSynthSmocked : longSynthSmocked
                                                            ).contents);
                                                        return Chai.recordArrayDeepEqualFlat(undefined, transferCalls, []);
                                                      }));
                                        }));
                                  it("should not emit the ExecuteNextPriceRedeemSettlementUser event", (function () {
                                          return Chai.expectToNotEmit(Chai.callEmitEvents(executeOutstandingNextPriceRedeemsTx.contents, contracts.contents.longShort, "ExecuteNextPriceRedeemSettlementUser"));
                                        }));
                                  
                                }));
                          describe("userNextPriceDepositAmount > 0", (function () {
                                  var executeOutstandingNextPriceRedeemsTx = {
                                    contents: "Undefined"
                                  };
                                  var userNextPrice_syntheticToken_toShiftAwayFrom_marketSide = Helpers.randomTokenAmount(undefined);
                                  var syntheticToken_priceSnapshotShiftedFrom = Helpers.randomTokenAmount(undefined);
                                  var syntheticToken_priceSnapshotShiftedTo = Helpers.randomTokenAmount(undefined);
                                  beforeEach(function () {
                                        return LetOps.Await.let_(setup(isShiftFromLong, userNextPrice_syntheticToken_toShiftAwayFrom_marketSide, Helpers.randomInteger(undefined), syntheticToken_priceSnapshotShiftedFrom, syntheticToken_priceSnapshotShiftedTo), (function (param) {
                                                      executeOutstandingNextPriceRedeemsTx.contents = contracts.contents.longShort._executeOutstandingNextPriceTokenShiftsExposed(marketIndex, user, isShiftFromLong);
                                                      
                                                    }));
                                      });
                                  it("should call transfer on the correct amount of Syntetic Tokens to the user", (function () {
                                          return LetOps.Await.let_(executeOutstandingNextPriceRedeemsTx.contents, (function (param) {
                                                        var transferCalls = SyntheticTokenSmocked.transferCalls((
                                                              isShiftFromLong ? shortSynthSmocked : longSynthSmocked
                                                            ).contents);
                                                        var expectedAmountOfPaymentTokenToRecieve = Contract.LongShortHelpers.calcAmountPaymentToken(userNextPrice_syntheticToken_toShiftAwayFrom_marketSide, syntheticToken_priceSnapshotShiftedFrom);
                                                        var expectedAmountOfOtherSyntheticTokenToRecieve = Contract.LongShortHelpers.calcAmountSyntheticToken(expectedAmountOfPaymentTokenToRecieve, syntheticToken_priceSnapshotShiftedTo);
                                                        return Chai.recordArrayDeepEqualFlat(undefined, transferCalls, [{
                                                                      recipient: user,
                                                                      amount: expectedAmountOfOtherSyntheticTokenToRecieve
                                                                    }]);
                                                      }));
                                        }));
                                  it("should emit the ExecuteNextPriceRedeemSettlementUser event with the correct arguments", (function () {
                                          var expectedAmountOfPaymentTokenToRecieve = Contract.LongShortHelpers.calcAmountPaymentToken(userNextPrice_syntheticToken_toShiftAwayFrom_marketSide, syntheticToken_priceSnapshotShiftedFrom);
                                          var expectedAmountOfOtherSyntheticTokenToRecieve = Contract.LongShortHelpers.calcAmountSyntheticToken(expectedAmountOfPaymentTokenToRecieve, syntheticToken_priceSnapshotShiftedTo);
                                          return Chai.callEmitEvents(executeOutstandingNextPriceRedeemsTx.contents, contracts.contents.longShort, "ExecuteNextPriceMarketSideShiftSettlementUser").withArgs(user, marketIndex, isShiftFromLong, expectedAmountOfOtherSyntheticTokenToRecieve);
                                        }));
                                  it("should reset userNextPrice_syntheticToken_toShiftAwayFrom_marketSide to zero", (function () {
                                          return LetOps.Await.let_(contracts.contents.longShort.userNextPrice_syntheticToken_toShiftAwayFrom_marketSide(marketIndex, isShiftFromLong, user), (function (userNextPrice_syntheticToken_toShiftAwayFrom_marketSide) {
                                                        return Chai.bnEqual(undefined, Globals.zeroBn, userNextPrice_syntheticToken_toShiftAwayFrom_marketSide);
                                                      }));
                                        }));
                                  
                                }));
                          
                        };
                        describe("Long Side", (function () {
                                return testExecuteOutstandingNextPriceRedeems(true);
                              }));
                        describe("Short Side", (function () {
                                return testExecuteOutstandingNextPriceRedeems(false);
                              }));
                        
                      }));
                
              }));
}

exports.testUnit = testUnit;
/* Chai Not a pure module */
