/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IDiscountProfile,
  IDiscountProfileInterface,
} from "../IDiscountProfile";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "discount",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "numerator",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "denominator",
            type: "uint256",
          },
        ],
        internalType: "struct float",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IDiscountProfile__factory {
  static readonly abi = _abi;
  static createInterface(): IDiscountProfileInterface {
    return new utils.Interface(_abi) as IDiscountProfileInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDiscountProfile {
    return new Contract(address, _abi, signerOrProvider) as IDiscountProfile;
  }
}
