/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IGovernanceOwned,
  IGovernanceOwnedInterface,
} from "../IGovernanceOwned";

const _abi = [
  {
    inputs: [],
    name: "governance",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IGovernanceOwned__factory {
  static readonly abi = _abi;
  static createInterface(): IGovernanceOwnedInterface {
    return new utils.Interface(_abi) as IGovernanceOwnedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGovernanceOwned {
    return new Contract(address, _abi, signerOrProvider) as IGovernanceOwned;
  }
}
