/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MockCssrRouter,
  MockCssrRouterInterface,
} from "../MockCssrRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_asset",
        type: "address",
      },
    ],
    name: "getLiquidity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_asset",
        type: "address",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "numerator",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "denominator",
            type: "uint256",
          },
        ],
        internalType: "struct float",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "numerator",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_newPrice",
        type: "uint256",
      },
    ],
    name: "setPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_asset",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "update",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "numerator",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "denominator",
            type: "uint256",
          },
        ],
        internalType: "struct float",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061030b806100206000396000f3fe608060405234801561001057600080fd5b50600436106100565760003560e01c8062e4768b1461005b57806302a688ed1461008757806341976e09146100ba5780638fdb8630146100cd578063a747b93b146100fb575b600080fd5b6100856100693660046102be565b6001600160a01b03909116600090815260208190526040902055565b005b61009a6100953660046101fc565b61011b565b604080518251815260209283015192810192909252015b60405180910390f35b61009a6100c83660046101e1565b61013f565b6100ed6100db3660046101e1565b60006020819052908152604090205481565b6040519081526020016100b1565b6100ed6101093660046101e1565b506c0c9f2c9cd04674edea4000000090565b60408051808201909152600080825260208201526101388361013f565b9392505050565b60408051808201909152600080825260208201526001600160a01b03821660009081526020819052604090205461019057505060408051808201909152670de0b6b3a7640000808252602082015290565b506040805180820182526001600160a01b0390921660009081526020818152919020548252670de0b6b3a76400009082015290565b919050565b80356001600160a01b03811681146101c557600080fd5b6000602082840312156101f357600080fd5b610138826101ca565b6000806040838503121561020f57600080fd5b610218836101ca565b9150602083013567ffffffffffffffff8082111561023557600080fd5b818501915085601f83011261024957600080fd5b81358181111561025b5761025b6102e8565b604051601f8201601f19908116603f01168101908382118183101715610283576102836102e8565b8160405282815288602084870101111561029c57600080fd5b8260208601602083013760006020848301015280955050505050509250929050565b600080604083850312156102d157600080fd5b6102da836101ca565b946020939093013593505050565b634e487b7160e01b600052604160045260246000fdfea164736f6c6343000807000a";

export class MockCssrRouter__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MockCssrRouter> {
    return super.deploy(overrides || {}) as Promise<MockCssrRouter>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MockCssrRouter {
    return super.attach(address) as MockCssrRouter;
  }
  connect(signer: Signer): MockCssrRouter__factory {
    return super.connect(signer) as MockCssrRouter__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockCssrRouterInterface {
    return new utils.Interface(_abi) as MockCssrRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockCssrRouter {
    return new Contract(address, _abi, signerOrProvider) as MockCssrRouter;
  }
}
