/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  NoDiscountProfile,
  NoDiscountProfileInterface,
} from "../NoDiscountProfile";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "discount",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "numerator",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "denominator",
            type: "uint256",
          },
        ],
        internalType: "struct float",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060bc8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063ce06898014602d575b600080fd5b606260383660046081565b50604080518082018252600080825260209182018190528251808401909352825260019082015290565b6040805182518152602092830151928101929092520160405180910390f35b600060208284031215609257600080fd5b81356001600160a01b038116811460a857600080fd5b939250505056fea164736f6c6343000807000a";

export class NoDiscountProfile__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<NoDiscountProfile> {
    return super.deploy(overrides || {}) as Promise<NoDiscountProfile>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): NoDiscountProfile {
    return super.attach(address) as NoDiscountProfile;
  }
  connect(signer: Signer): NoDiscountProfile__factory {
    return super.connect(signer) as NoDiscountProfile__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NoDiscountProfileInterface {
    return new utils.Interface(_abi) as NoDiscountProfileInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NoDiscountProfile {
    return new Contract(address, _abi, signerOrProvider) as NoDiscountProfile;
  }
}
