// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ethers = require("ethers");
var Random = require("random");
var Js_dict = require("rescript/lib/js/js_dict.js");
var Process = require("process");
var Seedrandom = require("seedrandom");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

var SeedRandom = {};

var Random$1 = {};

function fromMnemonic(mnemonic) {
  var counter = {
    contents: -1
  };
  return function (param) {
    counter.contents = counter.contents + 1 | 0;
    return Ethers.Wallet.fromMnemonic(mnemonic, "m/44'/60'/" + String(counter.contents) + "'/0/0", "en");
  };
}

var Generator = {
  fromMnemonic: fromMnemonic
};

var replaceCreateRandom = ((fn) => {
    require('ethers').Wallet.createRandom = fn;
  });

var Wallet = {
  Generator: Generator,
  replaceCreateRandom: replaceCreateRandom
};

function seedTestRng(seed) {
  Random.use(Seedrandom(seed));
  Random.patch();
  return replaceCreateRandom(fromMnemonic(seed));
}

function mochaSetup(param) {
  var seed = Belt_Option.getWithDefault(Belt_Option.flatMap(Js_dict.get(Process.env, "TEST_SEED_MNEMONIC"), (function (str) {
              if (str.length !== 0) {
                return str;
              }
              
            })), Ethers.Wallet.createRandom().mnemonic.phrase);
  seedTestRng(seed);
  console.log("Running tests with random seed: \"" + seed + "\"");
  
}

exports.SeedRandom = SeedRandom;
exports.Random = Random$1;
exports.Wallet = Wallet;
exports.seedTestRng = seedTestRng;
exports.mochaSetup = mochaSetup;
/* ethers Not a pure module */
