/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IMochiProfileInterface extends ethers.utils.Interface {
  functions: {
    "assetClass(address)": FunctionFragment;
    "calculateFeeIndex(address,uint256,uint256)": FunctionFragment;
    "changeAssetClass(address[],uint8[])": FunctionFragment;
    "changeLiquidityRequirement(uint256)": FunctionFragment;
    "changeMinimumDebt(uint256)": FunctionFragment;
    "creditCap(address)": FunctionFragment;
    "delay()": FunctionFragment;
    "keeperFee(address)": FunctionFragment;
    "liquidationFactor(address)": FunctionFragment;
    "liquidationFee(address)": FunctionFragment;
    "liquidityRequirement()": FunctionFragment;
    "maxCollateralFactor(address)": FunctionFragment;
    "minimumDebt()": FunctionFragment;
    "stabilityFee(address)": FunctionFragment;
    "utilizationRatio(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "assetClass", values: [string]): string;
  encodeFunctionData(
    functionFragment: "calculateFeeIndex",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeAssetClass",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "changeLiquidityRequirement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeMinimumDebt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "creditCap", values: [string]): string;
  encodeFunctionData(functionFragment: "delay", values?: undefined): string;
  encodeFunctionData(functionFragment: "keeperFee", values: [string]): string;
  encodeFunctionData(
    functionFragment: "liquidationFactor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationFee",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityRequirement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxCollateralFactor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "minimumDebt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stabilityFee",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "utilizationRatio",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "assetClass", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateFeeIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeAssetClass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeLiquidityRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeMinimumDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creditCap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keeperFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidationFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxCollateralFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stabilityFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "utilizationRatio",
    data: BytesLike
  ): Result;

  events: {};
}

export class IMochiProfile extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IMochiProfileInterface;

  functions: {
    assetClass(_asset: string, overrides?: CallOverrides): Promise<[number]>;

    calculateFeeIndex(
      _asset: string,
      _currentIndex: BigNumberish,
      _lastAccrued: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    changeAssetClass(
      _asset: string[],
      _class: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeLiquidityRequirement(
      _requirement: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeMinimumDebt(
      _debt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    creditCap(_asset: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    delay(overrides?: CallOverrides): Promise<[BigNumber]>;

    keeperFee(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber] & {
          numerator: BigNumber;
          denominator: BigNumber;
        }
      ]
    >;

    liquidationFactor(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber] & {
          numerator: BigNumber;
          denominator: BigNumber;
        }
      ]
    >;

    liquidationFee(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber] & {
          numerator: BigNumber;
          denominator: BigNumber;
        }
      ]
    >;

    liquidityRequirement(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxCollateralFactor(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber] & {
          numerator: BigNumber;
          denominator: BigNumber;
        }
      ]
    >;

    minimumDebt(overrides?: CallOverrides): Promise<[BigNumber]>;

    stabilityFee(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber] & {
          numerator: BigNumber;
          denominator: BigNumber;
        }
      ]
    >;

    utilizationRatio(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber] & {
          numerator: BigNumber;
          denominator: BigNumber;
        }
      ]
    >;
  };

  assetClass(_asset: string, overrides?: CallOverrides): Promise<number>;

  calculateFeeIndex(
    _asset: string,
    _currentIndex: BigNumberish,
    _lastAccrued: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  changeAssetClass(
    _asset: string[],
    _class: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeLiquidityRequirement(
    _requirement: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeMinimumDebt(
    _debt: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  creditCap(_asset: string, overrides?: CallOverrides): Promise<BigNumber>;

  delay(overrides?: CallOverrides): Promise<BigNumber>;

  keeperFee(
    _asset: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
  >;

  liquidationFactor(
    _asset: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
  >;

  liquidationFee(
    _asset: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
  >;

  liquidityRequirement(overrides?: CallOverrides): Promise<BigNumber>;

  maxCollateralFactor(
    _asset: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
  >;

  minimumDebt(overrides?: CallOverrides): Promise<BigNumber>;

  stabilityFee(
    _asset: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
  >;

  utilizationRatio(
    _asset: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
  >;

  callStatic: {
    assetClass(_asset: string, overrides?: CallOverrides): Promise<number>;

    calculateFeeIndex(
      _asset: string,
      _currentIndex: BigNumberish,
      _lastAccrued: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    changeAssetClass(
      _asset: string[],
      _class: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    changeLiquidityRequirement(
      _requirement: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    changeMinimumDebt(
      _debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    creditCap(_asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    delay(overrides?: CallOverrides): Promise<BigNumber>;

    keeperFee(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
    >;

    liquidationFactor(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
    >;

    liquidationFee(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
    >;

    liquidityRequirement(overrides?: CallOverrides): Promise<BigNumber>;

    maxCollateralFactor(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
    >;

    minimumDebt(overrides?: CallOverrides): Promise<BigNumber>;

    stabilityFee(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
    >;

    utilizationRatio(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
    >;
  };

  filters: {};

  estimateGas: {
    assetClass(_asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    calculateFeeIndex(
      _asset: string,
      _currentIndex: BigNumberish,
      _lastAccrued: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    changeAssetClass(
      _asset: string[],
      _class: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeLiquidityRequirement(
      _requirement: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeMinimumDebt(
      _debt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    creditCap(_asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    delay(overrides?: CallOverrides): Promise<BigNumber>;

    keeperFee(_asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    liquidationFactor(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidationFee(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidityRequirement(overrides?: CallOverrides): Promise<BigNumber>;

    maxCollateralFactor(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    minimumDebt(overrides?: CallOverrides): Promise<BigNumber>;

    stabilityFee(_asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    utilizationRatio(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    assetClass(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateFeeIndex(
      _asset: string,
      _currentIndex: BigNumberish,
      _lastAccrued: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    changeAssetClass(
      _asset: string[],
      _class: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeLiquidityRequirement(
      _requirement: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeMinimumDebt(
      _debt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    creditCap(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    delay(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    keeperFee(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidationFactor(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidationFee(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidityRequirement(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxCollateralFactor(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minimumDebt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stabilityFee(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    utilizationRatio(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
